## np array vs python list
- datatypes - same data types only vs mixed allowed
- performance - much faster vs slower
- memory efficiency - high vs low
- vector operations - Easy + fast vs manual loops
 

In [1]:
import numpy as np 

## Basic Array creation

In [4]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:
d2_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(d2_arr)

[[1 2 3]
 [4 5 6]]


## Generating Array

In [6]:
arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [7]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr = np.linspace(1,5,20)
print(arr)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


## Random number Generation

In [ ]:
arr = np.random.rand(5) # output will be between 0 and 1
print(arr)

[0.16152261 0.13682981 0.63975515 0.81149618 0.56646922]


In [ ]:
arr = np.random.randn(5) # output will be between -3 and 3
print(arr)

[-1.21503409 -0.84942376  0.5481206  -1.21465705 -0.45790236]


In [15]:
arr = np.random.randint(0, 10, (3, 3))
print(arr)

[[8 3 6]
 [6 5 8]
 [0 5 4]]


## Array attributes

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [18]:
arr.dtype

dtype('int32')

## Array methods

In [19]:
arr.min()

np.int32(0)

In [21]:
arr.max()

np.int32(8)

In [22]:
arr.sum()

np.int64(45)

In [23]:
arr.sum(axis=0) # column wise sum

array([14, 13, 18])

In [24]:
arr.sum(axis=1) # row wise sum

array([17, 19,  9])

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
arr.std()

np.float64(2.3570226039551585)

In [ ]:
arr.argmax() # index of maximum value

np.int64(0)

In [28]:
arr.argmin() # index of minimum value

np.int64(6)

## Reshaping and resizing


In [29]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Numpy indexing and slicing of vectors

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[9] # accessing 10th element using indexing

np.int64(10)

In [ ]:
arr[1:6:1] #[start:stop:step] slicing

array([2, 3, 4, 5, 6])

## Numpy indexing and slicing of matrix

In [61]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
arr[3,4] # accessing element at 4th row and 5th column

np.int64(20)

In [55]:
arr[0:2, 1:3] # slicing 2D array

array([[2, 3],
       [7, 8]])

In [ ]:
slice = arr[1:4, 3:5] # slicing 2D array, this will create a view of the original array, not a copy
print(slice)

[[ 9 10]
 [14 15]
 [19 20]]


## Boolean indexing

In [ ]:
bool_index = arr % 2 != 0 # boolean indexing to get odd numbers
print(bool_index)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


In [ ]:
arr = arr[bool_index] # using boolean indexing to get odd numbers from the array
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]
