## np array vs python list
- datatypes - same data types only vs mixed allowed
- performance - much faster vs slower
- memory efficiency - high vs low
- vector operations - Easy + fast vs manual loops
 

In [1]:
import numpy as np 

## Basic Array creation

In [4]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:
d2_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(d2_arr)

[[1 2 3]
 [4 5 6]]


## Generating Array

In [6]:
arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [7]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr = np.linspace(1,5,20)
print(arr)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


## Random number Generation

In [ ]:
arr = np.random.rand(5) # output will be between 0 and 1
print(arr)

[0.16152261 0.13682981 0.63975515 0.81149618 0.56646922]


In [ ]:
arr = np.random.randn(5) # output will be between -3 and 3
print(arr)

[-1.21503409 -0.84942376  0.5481206  -1.21465705 -0.45790236]


In [15]:
arr = np.random.randint(0, 10, (3, 3))
print(arr)

[[8 3 6]
 [6 5 8]
 [0 5 4]]


## Array attributes

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [18]:
arr.dtype

dtype('int32')

## Array methods

In [19]:
arr.min()

np.int32(0)

In [21]:
arr.max()

np.int32(8)

In [22]:
arr.sum()

np.int64(45)

In [23]:
arr.sum(axis=0) # column wise sum

array([14, 13, 18])

In [24]:
arr.sum(axis=1) # row wise sum

array([17, 19,  9])

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
arr.std()

np.float64(2.3570226039551585)

In [ ]:
arr.argmax() # index of maximum value

np.int64(0)

In [28]:
arr.argmin() # index of minimum value

np.int64(6)

## Reshaping and resizing


In [29]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Numpy indexing and slicing of vectors

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[9] # accessing 10th element using indexing

np.int64(10)

In [ ]:
arr[1:6:1] #[start:stop:step] slicing

array([2, 3, 4, 5, 6])

## Numpy indexing and slicing of matrix

In [61]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
arr[3,4] # accessing element at 4th row and 5th column

np.int64(20)

In [55]:
arr[0:2, 1:3] # slicing 2D array

array([[2, 3],
       [7, 8]])

In [ ]:
slice = arr[1:4, 3:5] # slicing 2D array, this will create a view of the original array, not a copy
print(slice)

[[ 9 10]
 [14 15]
 [19 20]]


## Boolean indexing

In [ ]:
bool_index = arr % 2 != 0 # boolean indexing to get odd numbers
print(bool_index)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


In [ ]:
arr = arr[bool_index] # using boolean indexing to get odd numbers from the array
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


## Array operation

In [3]:
import numpy as np
arr1 = np.arange(1, 11)
arr2 = np.arange(11, 21)

In [4]:
sum = arr1 + arr2
print(sum)

[12 14 16 18 20 22 24 26 28 30]


In [5]:
minus = arr2 - arr1
print(minus)

[10 10 10 10 10 10 10 10 10 10]


In [6]:
multiple = arr1 * arr2
print(multiple)

[ 11  24  39  56  75  96 119 144 171 200]


In [7]:
div = arr2 / arr1
print(div)

[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ]


In [8]:
floor_div = arr2 // arr1
print(floor_div)

[11  6  4  3  3  2  2  2  2  2]


In [9]:
power = arr2 ** arr1
print(power)

[            11            144           2197          38416
         759375       16777216      410338673    11019960576
   322687697779 10240000000000]


## Broadcasting

In [10]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)


In [ ]:
# adding 10 to each element of the list using loop
for num in l:
    num = num + 10
    print(num)


11
12
13
14
15


In [14]:
arr + 10 # adding 10 to each element of the array using broadcasting

array([11, 12, 13, 14, 15])

## Deep and Shallow copy

In [15]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice = a[2:7]
slice = slice * 10
slice

array([30, 40, 50, 60, 70])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
b[0] = 99

In [25]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Matrix operation

In [27]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[1,2],[3,4]])



In [28]:
import numpy as np
np.dot(mat1,mat2)

array([[ 7, 10],
       [15, 22]])

In [29]:
np.transpose(mat1)

array([[1, 3],
       [2, 4]])

## Advance array manipulation

### Stacking array

In [ ]:
np.hstack((mat1,mat2)) # order of the row should be same

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
np.vstack((mat1,mat2)) # order of the column should be same

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [33]:
np.column_stack((mat1,mat2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Splitting array

In [38]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.hsplit(arr,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [42]:
np.vsplit(arr,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [6]:
import numpy as np
a  = np.array(5)

## Dimension Shape and Size

In [7]:
print(a.ndim )# number of dimensions
print(a.shape) # shape of the array
print(a.size )# total number of elements in the array

0
()
1


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr.ndim )# number of dimensions
print(arr.shape) # shape of the array
print(arr.size )# total number of elements in the array

1
(5,)
5


In [8]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
print(b.ndim )# number of dimensions
print(b.shape) # shape of the array
print(b.size )# total number of elements in the array

2
(2, 3)
6


In [30]:
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]], [[10, 11, 12], [13, 14, 15], [19, 20, 21],[22,23,24]]])


In [31]:
print(c.ndim )# number of dimensions
print(c.shape) # shape of the array
print(c.size )# total number of elements in the array

3
(2, 4, 3)
24
